# -*- coding: utf-8 -*-
"""[Adilson junior]Atividade Avaliativa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRFxMMDx7RF6lC5EduErzIJ2bvVh-8BF
"""

!pip install liqfit

from liqfit.pipeline import ZeroShotClassificationPipeline
from liqfit.models import T5ForZeroShotClassification
from transformers import T5Tokenizer
import pandas as pd

modelo = T5ForZeroShotClassification.from_pretrained('knowledgator/comprehend_it-multilingual-t5-base')
tokenizador = T5Tokenizer.from_pretrained('knowledgator/comprehend_it-multilingual-t5-base')
classificador = ZeroShotClassificationPipeline(model=modelo, tokenizer=tokenizador, hypothesis_template='{}', encoder_decoder=True)

file_path = '/content/descricoes_produtos.csv'
df = pd.read_csv(file_path)

categorias = ['brinquedos', 'beleza', 'eletrônicos', 'ferramentas', 'cozinha']

def categorizar_produto(descricao):
    result = classificador(descricao, candidate_labels=categorias)
    return result['labels'][0]

df['Categoria'] = df['Descrição'].apply(categorizar_produto)

print(df)

df.to_csv('produtos_categorizados.csv', index=False)