# -*- coding: utf-8 -*-
"""Images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWCtV63r2GfypuXaNCx_e3ZsMjdlhF-B
"""

from transformers import pipeline
image_path = "https://farm5.staticflickr.com/4007/4322154488_997e69e4cf_z.jpg"
pipe = pipeline("image-segmentation", model="briaai/RMBG-1.4",
trust_remote_code=True)
pillow_mask = pipe(image_path, return_mask = True) # outputs a pillow mask
pillow_image = pipe(image_path) # applies mask on input and returns a pillow image

image_path = '/content/camera_fotografica.jpg'
pipe = pipeline('image-segmentation', model='briaai/RMBG-1.4',
trust_remote_code=True)
pillow_mask = pipe(image_path, return_mask = True) # outputs a pillow mask
pillow_image = pipe(image_path) # applies mask on input and returns a pillow image
pillow_mask

pip install gradio

import gradio as gr
from transformers import pipeline
from PIL import Image
# Função para remover o background da imagem
def remove_background(image):
  pipe = pipeline("image-segmentation", model="briaai/RMBG-1.4",
  trust_remote_code=True)
  # Obter a máscara da imagem
  pillow_mask = pipe(image, return_mask=True)
  # Aplicar máscara na imagem original
  pillow_image = pipe(image)
  return pillow_image

import gradio as gr
from transformers import pipeline
from PIL import Image
# Função para remover o background da imagem
def remove_background(image):
  pipe = pipeline("image-segmentation", model="briaai/RMBG-1.4", trust_remote_code=True)
  # Obter a máscara da imagem
  pillow_mask = pipe(image, return_mask=True)
  # Aplicar máscara na imagem original
  pillow_image = pipe(image)
  return pillow_image
  # Criar uma interface Gradio
  app = gr.Interface(
  fn=remove_background,
  inputs=gr.components.Image(type="pil"),
  outputs=gr.components.Image(type="pil", format="png"), # Especificar saída como PNG
  title="Remoção de Background de Imagens",
  description="Envie uma imagem e veja o background sendo removido automaticamente. A imagem resultante será no formato PNG."
  )
  app.launch(share=True)